name: Docker test and publish

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-publish:
    env:
      PUPPERWARE_ANALYTICS_STREAM: production
      IS_LATEST: true
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem install bundler
      - name: Set custom latest version
        if: endsWith(github.ref, '/6.4.x')
        run: echo "::set-env name=LATEST_VERSION::6.4"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-push-image                
        id: docker_build 
        uses: docker/build-push-action@v2
        with:
            context: ./docker/puppet-agent-ubuntu
            file: ./docker/puppet-agent-ubuntu/Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: abhay900/puppetagent:latest
      - name: Build container
        working-directory: docker
        run: |
          docker system prune --all --force --volumes
          docker builder prune --force --keep-storage=10GB
          make lint build test
      - name: Publish container
        working-directory: docker
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          make publish
      
