name: Docker test and publish

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem install bundler
      - uses: actions/checkout@v2
      - name: Set up QEMU
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker hub
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: build-push-image                  
        id: docker_build 
        uses: docker/build-push-action@v2
      - name: Set custom latest version
        if: endsWith(github.ref, '/6.4.x')
        run: echo "::set-env name=LATEST_VERSION::6.4"
      - name: Build container
        working-directory: docker
        run: |
          docker system prune --all --force --volumes
          docker builder prune --force --keep-storage=10GB
          make lint build test
      - name: Publish container
        working-directory: docker
        run: |
          docker login -u abhay900 -p abhay12
          make publish
